import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';

import '../providers/settings_manager.dart';

const Map<String, Map<String, String>> translations = {
  'en': {
    'profile': 'Profile',
    'settings': 'Settings',
    'achievements': 'Achievements',
    'language': 'Language',
    'text_size': 'Text Size',
    'theme_color': 'Theme Color',
    'dark_mode': 'Dark Mode',
    'continue': 'Continue',
    'save': 'Save',
    'edit': 'Edit',
    'start': 'Start',
    'menu': 'Menu',
    'about_mental_health': 'About Mental Health',
    'switch_theme_vibe': 'Switch themes to match your vibe.',
    'audio': 'Audio',
    'control_audio': 'Control music and sound effects.',
    'music_volume': 'Music Volume',
    'sound_effects': 'Sound Effects',
    'adjust_text': 'Adjust how text appears.',
    'preview_text_size': 'Preview text size',
    'choose_language': 'Choose your preferred language.',
    'theme_colors': 'Theme Colors',
    'pick_visual_style': 'Pick your visual style.',
    'sign_out': 'Sign Out',
    'sign_out_confirm': 'Are you sure you want to sign out?',
    'cancel': 'Cancel',
    'choose_story': 'Choose a Story',
    'pick_feeling': 'Pick what you are feeling',
    'pick_story_mood': 'No pressure. Just choose a story that matches your mood.',
    'the_day_after': 'The Space You Left',
    'what_still_remains': 'What Still Remains',
    'alone_again': 'Alone, Again',
    'almost_there': 'Almost There',
    'too_loud_inside': 'Too Loud Inside',
    'summary': 'Summary',
    'the_end': 'The End',
    'replay_story': 'Replay Story',
    'save_quit': 'Save & Quit',
    'sign_in': 'Sign In',
    'create_account': 'Create Account',
    'email': 'Email',
    'password': 'Password',
    'name': 'Name',
    'gender': 'Gender',
    'date_of_birth': 'Date of Birth',
    'garden': 'Garden',
    'garden_title': 'Your Garden',
    'garden_water': 'Water',
    'garden_pick_title': 'Choose a plant',
    'garden_pick_subtitle':
        'Pick one to start. You can nurture it over time.',
    'garden_cooldown': 'Come back in {time} to water again.',
    'garden_water_wait': 'Water in {time}',
    'garden_come_back_in': 'Come back in {time}',
    'garden_fully_grown_cta': 'Fully grown',
    'garden_pick_again_title': 'Your garden',
    'garden_pick_again_subtitle':
        'Pick a plant to grow next, or restart one you’ve finished before.',
    'garden_reset_same_title': 'This plant is already fully grown',
    'garden_reset_same_body':
        'Reset it to start growing again, or keep it as it is?',
    'garden_reset_plant': 'Reset plant',
    'garden_keep_as_is': 'Keep as it is',
    'garden_full_grown': 'Fully grown — enjoy the calm.',
    'garden_watered': 'Watered. Your plant feels a little stronger.',
    'explore_collections': 'Explore Collections',
    'daily_check_in': 'Daily Check-in',
    'my_space': 'My Space',
    'continue_where_left': 'Continue where you left off',
    'no_unfinished_stories': 'No unfinished stories',
    'start_new_story': 'Start a new story',
    'scene': 'Scene',
    'story_not_available': 'This story is not available yet.',
    'start_story': 'Start Story',
    'take_your_time_stop_anytime': 'Take your time. You can stop anytime.',
    'username': 'Username',
    'enter_name': 'Enter name',
    'details': 'Details',
    'not_available': 'Not available',
    'mood': 'Mood',
    'stories_completed': 'Stories Completed',
    'last_story': 'Last Story',
    'choose_from_device': 'Choose from device',
    'use_default_avatar': 'Use default avatar',
    'select_gender': 'Select gender',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'pick_a_date': 'Pick a date',
    'based_on_last_story': 'Based on last story',
    'calm': 'Calm',
    'anxious': 'Anxious',
    'no_achievements_yet': 'No achievements yet.',
    'achieved': 'Achieved!',
    'locked': 'Locked',
    'badge_locked_keep_exploring':
        'This badge is still locked.\nKeep exploring stories to unlock it.',
    'none': 'None',
    'emotion': 'Emotion',
    'fertilizer': 'Fertilizer',
    'no_fertilizer_left': 'No fertilizer left.',
    'no_growth_time_to_reduce': 'No growth time to reduce.',
    'growth_time_reduced': 'Growth time reduced',
    'saving': 'Saving...',
    'theme_violet': 'Violet',
    'theme_sky': 'Sky',
    'theme_forest': 'Forest',
    'theme_honey': 'Honey',
    'theme_sakura': 'Sakura',
    'theme_cherry': 'Cherry',
    'theme_ash': 'Ash',
  },
  'tr': {
    'profile': 'Profil',
    'settings': 'Ayarlar',
    'achievements': 'Basarilar',
    'language': 'Dil',
    'text_size': 'Metin Boyutu',
    'theme_color': 'Tema Rengi',
    'dark_mode': 'Koyu Mod',
    'continue': 'Devam',
    'save': 'Kaydet',
    'edit': 'Duzenle',
    'start': 'Basla',
    'menu': 'Menu',
    'about_mental_health': 'Ruh Sagligi Hakkinda',
    'switch_theme_vibe': 'Temayi ruh haline gore degistir.',
    'audio': 'Ses',
    'control_audio': 'Muzik ve efekt sesini kontrol et.',
    'music_volume': 'Muzik Seviyesi',
    'sound_effects': 'Ses Efektleri',
    'adjust_text': 'Yazinin gorunumunu ayarla.',
    'preview_text_size': 'Onizleme yazi boyutu',
    'choose_language': 'Tercih ettigin dili sec.',
    'theme_colors': 'Tema Renkleri',
    'pick_visual_style': 'Gorsel tarzini sec.',
    'sign_out': 'Cikis Yap',
    'sign_out_confirm': 'Cikis yapmak istediginize emin misiniz?',
    'cancel': 'Iptal',
    'choose_story': 'Bir Hikaye Sec',
    'pick_feeling': 'Nasil hissettigini sec',
    'pick_story_mood': 'Baski yok. Ruh haline uygun bir hikaye sec.',
    'the_day_after': 'Bıraktığın Boşluk',
    'what_still_remains': 'Geriye Kalan',
    'alone_again': 'Yine Yalniz',
    'almost_there': 'Neredeyse',
    'too_loud_inside': 'Icim Cok Gurultulu',
    'summary': 'Ozet',
    'the_end': 'Son',
    'replay_story': 'Hikayeyi Tekrar Oyna',
    'save_quit': 'Kaydet ve Cik',
    'sign_in': 'Giris Yap',
    'create_account': 'Hesap Olustur',
    'email': 'E-posta',
    'password': 'Sifre',
    'name': 'Isim',
    'gender': 'Cinsiyet',
    'date_of_birth': 'Dogum Tarihi',
    'garden': 'Bahce',
    'garden_title': 'Bahcen',
    'garden_water': 'Sula',
    'garden_pick_title': 'Bir bitki sec',
    'garden_pick_subtitle':
        'Baslamak icin birini sec. Zamanla buyutabilirsin.',
    'garden_cooldown': 'Tekrar sulamak icin {time} bekle.',
    'garden_water_wait': 'Sulama: {time}',
    'garden_come_back_in': 'Geri gel: {time}',
    'garden_fully_grown_cta': 'Tam buyudu',
    'garden_pick_again_title': 'Bahcen',
    'garden_pick_again_subtitle':
        'Siradaki bitkiyi sec veya tamamladigin birini yeniden baslat.',
    'garden_reset_same_title': 'Bu bitki zaten tam buyudu',
    'garden_reset_same_body':
        'Yeniden buyumeye baslatsin mi, yoksa boyle kalsin mi?',
    'garden_reset_plant': 'Sifirla',
    'garden_keep_as_is': 'Oldugu gibi kalsin',
    'garden_full_grown': 'Tam buyudu — sakinligi tadini cikar.',
    'garden_watered': 'Sulandi. Bitkin biraz daha guclu hissediyor.',
    'explore_collections': 'Koleksiyonlari Kesfet',
    'daily_check_in': 'Gunluk Check-in',
    'my_space': 'Alanim',
    'continue_where_left': 'Kaldigin yerden devam et',
    'no_unfinished_stories': 'Yarim kalan hikaye yok',
    'start_new_story': 'Yeni hikaye baslat',
    'scene': 'Sahne',
    'story_not_available': 'Bu hikaye su anda mevcut degil.',
    'start_story': 'Hikayeyi Baslat',
    'take_your_time_stop_anytime': 'Acele etme. Istedigin zaman durabilirsin.',
    'username': 'Kullanici adi',
    'enter_name': 'Isim gir',
    'details': 'Detaylar',
    'not_available': 'Mevcut degil',
    'mood': 'Ruh hali',
    'stories_completed': 'Tamamlanan hikayeler',
    'last_story': 'Son hikaye',
    'choose_from_device': 'Cihazdan sec',
    'use_default_avatar': 'Varsayilan avatari kullan',
    'select_gender': 'Cinsiyet sec',
    'male': 'Erkek',
    'female': 'Kadin',
    'other': 'Diger',
    'pick_a_date': 'Tarih sec',
    'based_on_last_story': 'Son hikayeye gore',
    'calm': 'Sakin',
    'anxious': 'Kaygili',
    'no_achievements_yet': 'Henuz basari yok.',
    'achieved': 'Kazanildi!',
    'locked': 'Kilitli',
    'badge_locked_keep_exploring':
        'Bu rozet henuz kilitli.\nAcmak icin hikayeleri kesfetmeye devam et.',
    'none': 'Yok',
    'emotion': 'Duygu',
    'fertilizer': 'Gubre',
    'no_fertilizer_left': 'Gubre kalmadi.',
    'no_growth_time_to_reduce': 'Azaltilacak buyume suresi yok.',
    'growth_time_reduced': 'Buyume suresi azaltildi',
    'saving': 'Kaydediliyor...',
    'theme_violet': 'Menekse',
    'theme_sky': 'Gokyuzu',
    'theme_forest': 'Orman',
    'theme_honey': 'Bal',
    'theme_sakura': 'Sakura',
    'theme_cherry': 'Kiraz',
    'theme_ash': 'Kul',
  },
  'ar': {
    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'achievements': 'الإنجازات',
    'language': 'اللغة',
    'text_size': 'حجم النص',
    'theme_color': 'لون السمة',
    'dark_mode': 'الوضع الداكن',
    'continue': 'متابعة',
    'save': 'حفظ',
    'edit': 'تعديل',
    'start': 'ابدأ',
    'menu': 'القائمة',
    'about_mental_health': 'حول الصحة النفسية',
    'switch_theme_vibe': 'غيّر السمة بما يناسب مزاجك.',
    'audio': 'الصوت',
    'control_audio': 'تحكم بالموسيقى والمؤثرات الصوتية.',
    'music_volume': 'مستوى الموسيقى',
    'sound_effects': 'المؤثرات الصوتية',
    'adjust_text': 'اضبط طريقة عرض النص.',
    'preview_text_size': 'معاينة حجم النص',
    'choose_language': 'اختر لغتك المفضلة.',
    'theme_colors': 'ألوان السمة',
    'pick_visual_style': 'اختر النمط البصري.',
    'sign_out': 'تسجيل الخروج',
    'sign_out_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'cancel': 'إلغاء',
    'choose_story': 'اختر قصة',
    'pick_feeling': 'اختر ما تشعر به',
    'pick_story_mood': 'بدون ضغط. اختر قصة تناسب حالتك.',
    'the_day_after': 'المساحة التي تركتها',
    'what_still_remains': 'ما تبقّى',
    'alone_again': 'وحيدًا مرة أخرى',
    'almost_there': 'اقتربت كثيرًا',
    'too_loud_inside': 'ضجيج داخلي',
    'summary': 'الملخص',
    'the_end': 'النهاية',
    'replay_story': 'إعادة القصة',
    'save_quit': 'حفظ وإنهاء',
    'sign_in': 'تسجيل الدخول',
    'create_account': 'إنشاء حساب',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'name': 'الاسم',
    'gender': 'الجنس',
    'date_of_birth': 'تاريخ الميلاد',
    'garden': 'الحديقة',
    'garden_title': 'حديقتك',
    'garden_water': 'اسقِ',
    'garden_pick_title': 'اختر نبتة',
    'garden_pick_subtitle': 'اختر واحدة للبدء. يمكنك العناية بها مع الوقت.',
    'garden_cooldown': 'عد بعد {time} لتسقي مرة أخرى.',
    'garden_water_wait': 'السقي بعد {time}',
    'garden_come_back_in': 'عد بعد {time}',
    'garden_fully_grown_cta': 'نمت بالكامل',
    'garden_pick_again_title': 'حديقتك',
    'garden_pick_again_subtitle':
        'اختر نبتة لتنمو لاحقًا أو أعد تشغيل واحدة أنهيتها من قبل.',
    'garden_reset_same_title': 'هذه النبتة نمت بالكامل بالفعل',
    'garden_reset_same_body': 'هل تريد إعادة ضبطها لتنمو مجددًا أم تركها كما هي؟',
    'garden_reset_plant': 'إعادة ضبط النبتة',
    'garden_keep_as_is': 'اتركها كما هي',
    'garden_full_grown': 'نمت بالكامل — استمتع بالهدوء.',
    'garden_watered': 'تم السقي. نبتتك أصبحت أقوى قليلًا.',
    'explore_collections': 'استكشف المجموعات',
    'daily_check_in': 'تسجيل يومي',
    'my_space': 'مساحتي',
    'continue_where_left': 'تابع من حيث توقفت',
    'no_unfinished_stories': 'لا توجد قصص غير مكتملة',
    'start_new_story': 'ابدأ قصة جديدة',
    'scene': 'المشهد',
    'story_not_available': 'هذه القصة غير متاحة حاليًا.',
    'start_story': 'ابدأ القصة',
    'take_your_time_stop_anytime': 'خذ وقتك. يمكنك التوقف في أي وقت.',
    'username': 'اسم المستخدم',
    'enter_name': 'أدخل الاسم',
    'details': 'التفاصيل',
    'not_available': 'غير متاح',
    'mood': 'المزاج',
    'stories_completed': 'القصص المكتملة',
    'last_story': 'آخر قصة',
    'choose_from_device': 'اختر من الجهاز',
    'use_default_avatar': 'استخدم الصورة الافتراضية',
    'select_gender': 'اختر الجنس',
    'male': 'ذكر',
    'female': 'أنثى',
    'other': 'آخر',
    'pick_a_date': 'اختر تاريخًا',
    'based_on_last_story': 'بناءً على آخر قصة',
    'calm': 'هادئ',
    'anxious': 'قلِق',
    'no_achievements_yet': 'لا توجد إنجازات بعد.',
    'achieved': 'تم الإنجاز!',
    'locked': 'مغلق',
    'badge_locked_keep_exploring':
        'هذا الوسام ما زال مغلقًا.\nاستمر في استكشاف القصص لفتحه.',
    'none': 'لا يوجد',
    'emotion': 'العاطفة',
    'fertilizer': 'السماد',
    'no_fertilizer_left': 'لا يوجد سماد متبقٍ.',
    'no_growth_time_to_reduce': 'لا يوجد وقت نمو لتقليله.',
    'growth_time_reduced': 'تم تقليل وقت النمو',
    'saving': 'جارٍ الحفظ...',
    'theme_violet': 'بنفسجي',
    'theme_sky': 'سماوي',
    'theme_forest': 'غابة',
    'theme_honey': 'عسلي',
    'theme_sakura': 'ساكورا',
    'theme_cherry': 'كرزي',
    'theme_ash': 'رمادي',
  },
};

String translate(BuildContext context, String key) {
  final lang = context.watch<SettingsManager>().language;
  return translations[lang]?[key] ?? translations['en']?[key] ?? key;
}

String t(BuildContext context, String key) => translate(context, key);

/// For async gaps and callbacks: [context.watch] is only valid during [State.build].
String tRead(BuildContext context, String key) {
  final lang = context.read<SettingsManager>().language;
  return translations[lang]?[key] ?? translations['en']?[key] ?? key;
}
