import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';

import '../providers/settings_manager.dart';

const Map<String, Map<String, String>> translations = {
  'en': {
    'profile': 'Profile',
    'settings': 'Settings',
    'achievements': 'Achievements',
    'language': 'Language',
    'text_size': 'Text Size',
    'theme_color': 'Theme Color',
    'dark_mode': 'Dark Mode',
    'continue': 'Continue',
    'save': 'Save',
    'edit': 'Edit',
    'start': 'Start',
    'menu': 'Menu',
    'about_mental_health': 'About Mental Health',
    'switch_theme_vibe': 'Switch themes to match your vibe.',
    'audio': 'Audio',
    'control_audio': 'Control music and sound effects.',
    'music_volume': 'Music Volume',
    'sound_effects': 'Sound Effects',
    'adjust_text': 'Adjust how text appears.',
    'preview_text_size': 'Preview text size',
    'choose_language': 'Choose your preferred language.',
    'theme_colors': 'Theme Colors',
    'pick_visual_style': 'Pick your visual style.',
    'sign_out': 'Sign Out',
    'sign_out_confirm': 'Are you sure you want to sign out?',
    'cancel': 'Cancel',
    'choose_story': 'Choose a Story',
    'pick_feeling': 'Pick what you are feeling',
    'pick_story_mood': 'No pressure. Just choose a story that matches your mood.',
    'the_day_after': 'The Space You Left',
    'what_still_remains': 'What Still Remains',
    'alone_again': 'Alone, Again',
    'almost_there': 'Almost There',
    'summary': 'Summary',
    'the_end': 'The End',
    'replay_story': 'Replay Story',
    'save_quit': 'Save & Quit',
    'sign_in': 'Sign In',
    'create_account': 'Create Account',
    'email': 'Email',
    'password': 'Password',
    'name': 'Name',
    'gender': 'Gender',
    'date_of_birth': 'Date of Birth',
    'garden': 'Garden',
    'garden_title': 'Your Garden',
    'garden_water': 'Water',
    'garden_pick_title': 'Choose a plant',
    'garden_pick_subtitle':
        'Pick one to start. You can nurture it over time.',
    'garden_cooldown': 'Come back in {time} to water again.',
    'garden_water_wait': 'Water in {time}',
    'garden_come_back_in': 'Come back in {time}',
    'garden_fully_grown_cta': 'Fully grown',
    'garden_pick_again_title': 'Your garden',
    'garden_pick_again_subtitle':
        'Pick a plant to grow next, or restart one you’ve finished before.',
    'garden_reset_same_title': 'This plant is already fully grown',
    'garden_reset_same_body':
        'Reset it to start growing again, or keep it as it is?',
    'garden_reset_plant': 'Reset plant',
    'garden_keep_as_is': 'Keep as it is',
    'garden_full_grown': 'Fully grown — enjoy the calm.',
    'garden_watered': 'Watered. Your plant feels a little stronger.',
  },
  'tr': {
    'profile': 'Profil',
    'settings': 'Ayarlar',
    'achievements': 'Basarilar',
    'language': 'Dil',
    'text_size': 'Metin Boyutu',
    'theme_color': 'Tema Rengi',
    'dark_mode': 'Koyu Mod',
    'continue': 'Devam',
    'save': 'Kaydet',
    'edit': 'Duzenle',
    'start': 'Basla',
    'menu': 'Menu',
    'about_mental_health': 'Ruh Sagligi Hakkinda',
    'switch_theme_vibe': 'Temayi ruh haline gore degistir.',
    'audio': 'Ses',
    'control_audio': 'Muzik ve efekt sesini kontrol et.',
    'music_volume': 'Muzik Seviyesi',
    'sound_effects': 'Ses Efektleri',
    'adjust_text': 'Yazinin gorunumunu ayarla.',
    'preview_text_size': 'Onizleme yazi boyutu',
    'choose_language': 'Tercih ettigin dili sec.',
    'theme_colors': 'Tema Renkleri',
    'pick_visual_style': 'Gorsel tarzini sec.',
    'sign_out': 'Cikis Yap',
    'sign_out_confirm': 'Cikis yapmak istediginize emin misiniz?',
    'cancel': 'Iptal',
    'choose_story': 'Bir Hikaye Sec',
    'pick_feeling': 'Nasil hissettigini sec',
    'pick_story_mood': 'Baski yok. Ruh haline uygun bir hikaye sec.',
    'the_day_after': 'Bıraktığın Boşluk',
    'what_still_remains': 'Geriye Kalan',
    'alone_again': 'Yine Yalniz',
    'almost_there': 'Neredeyse',
    'summary': 'Ozet',
    'the_end': 'Son',
    'replay_story': 'Hikayeyi Tekrar Oyna',
    'save_quit': 'Kaydet ve Cik',
    'sign_in': 'Giris Yap',
    'create_account': 'Hesap Olustur',
    'email': 'E-posta',
    'password': 'Sifre',
    'name': 'Isim',
    'gender': 'Cinsiyet',
    'date_of_birth': 'Dogum Tarihi',
    'garden': 'Bahce',
    'garden_title': 'Bahcen',
    'garden_water': 'Sula',
    'garden_pick_title': 'Bir bitki sec',
    'garden_pick_subtitle':
        'Baslamak icin birini sec. Zamanla buyutabilirsin.',
    'garden_cooldown': 'Tekrar sulamak icin {time} bekle.',
    'garden_water_wait': 'Sulama: {time}',
    'garden_come_back_in': 'Geri gel: {time}',
    'garden_fully_grown_cta': 'Tam buyudu',
    'garden_pick_again_title': 'Bahcen',
    'garden_pick_again_subtitle':
        'Siradaki bitkiyi sec veya tamamladigin birini yeniden baslat.',
    'garden_reset_same_title': 'Bu bitki zaten tam buyudu',
    'garden_reset_same_body':
        'Yeniden buyumeye baslatsin mi, yoksa boyle kalsin mi?',
    'garden_reset_plant': 'Sifirla',
    'garden_keep_as_is': 'Oldugu gibi kalsin',
    'garden_full_grown': 'Tam buyudu — sakinligi tadini cikar.',
    'garden_watered': 'Sulandi. Bitkin biraz daha guclu hissediyor.',
  },
};

String translate(BuildContext context, String key) {
  final lang = context.watch<SettingsManager>().language;
  return translations[lang]?[key] ?? translations['en']?[key] ?? key;
}

String t(BuildContext context, String key) => translate(context, key);

/// For async gaps and callbacks: [context.watch] is only valid during [State.build].
String tRead(BuildContext context, String key) {
  final lang = context.read<SettingsManager>().language;
  return translations[lang]?[key] ?? translations['en']?[key] ?? key;
}
